parsing:
  pred_days: 0.10
  URL: 'https://www.cbr.ru/hd_base/keyrate/?UniDbQuery.Posted=True&UniDbQuery.From=17.09.2013&UniDbQuery.To='

preprocessing:
  pred_days: 0.10
  drop_trash: 
  train_path: '../data/df_train.csv'
  test_path: '../data/df_test.csv'
  df_path: '../data/df.csv'
  
train:
  pred_days_forecast: 180
  backend_path: '../backend/src/data'
  data_path: '../data'
  model_path: '../models/prophet_best_model.joblib'
  params_path: '../models/prophet_best_params.joblib'
  metrics_path: '../report/metrics.json'
  dict_metrics_path: '../report/dict_metrics.json'
  train_path: '../data/df_train.csv'
  test_path: '../data/df_test.csv'
  df_path: '../data/df.csv'
  N_TRIALS: 5
  TIMEOUT: 1800

evaluate:
  predict_path: ../data/check/test.csv

frontend:
  main_image: '../data/frontend/main_image.png'

endpoints:
  train_test: 'http://localhost:8000/train_test'
  train_future: 'http://localhost:8000/train_future'
  # train_test: 'http://fastapi:8000/train'
  # train_future: 'http://fastapi:8000/train_future'