parcing:
  pred_days: 0.15
  URL: 'https://www.cbr.ru/hd_base/keyrate/?UniDbQuery.Posted=True&UniDbQuery.From=17.09.2013&UniDbQuery.To='

preprocessing:
  pred_days: 0.15
  random_sate: 42
  drop_trash: 
  
train:
  random_sate: 42
  pred_days_forecast: 180
  backend_path: '../backend/src/data'
  data_path: '../data'
  model_path: '../models'
  study_path: '../models/study.json'
  metrics_path: '..report/metrics.json'
  params_path: '..report/best_params.json'
  N_TRIALS: 1000
  TIMEOUT: 3600

evaluate:
  predict_path: ../data/check/test.csv

frontend:
  main_image: '../data/frontend/main_image.png'

endpoints:
  parcer: 'http://fatsapi:8000/parcer'
  train: 'http://fastapi:8000/train'
  prediction_test: 'http://fastapi:8000/prediction_test'
  prediction_future: 'http://fastapi:8000/prediction_future'